-- 80 paths
    ARRAY['Riyadh Region','Riyadh','Al Olaya'],
    ARRAY['Riyadh Region','Riyadh','Al Malaz'],
    ARRAY['Riyadh Region','Riyadh','Al Nakheel'],
    ARRAY['Riyadh Region','Riyadh','Al Murabba'],
    ARRAY['Riyadh Region','Riyadh','Al Sulaymaniyah'],
    ARRAY['Riyadh Region','Riyadh','Al Woroud'],
    ARRAY['Riyadh Region','Riyadh','Al Sahafa'],
    ARRAY['Riyadh Region','Al Kharj','Al Kharj Center'],
    ARRAY['Riyadh Region','Al Kharj','Al Rayyan'],
    ARRAY['Riyadh Region','Al Kharj','Al Yamama'],
    ARRAY['Riyadh Region','Al Majma''ah','Al Majma''ah Center'],
    ARRAY['Riyadh Region','Diriyah','Diriyah Center'],
    ARRAY['Riyadh Region','Diriyah','Al Bujairi'],
    ARRAY['Makkah Region','Jeddah','Al Hamra'],
    ARRAY['Makkah Region','Jeddah','Al Rawdah'],
    ARRAY['Makkah Region','Jeddah','Al Shati'],
    ARRAY['Makkah Region','Jeddah','Al Salamah'],
    ARRAY['Makkah Region','Jeddah','Al Andalus'],
    ARRAY['Makkah Region','Jeddah','Al Baghdadiyah'],
    ARRAY['Makkah Region','Mecca','Al Aziziyah'],
    ARRAY['Makkah Region','Mecca','Al Shubaikah'],
    ARRAY['Makkah Region','Mecca','Al Misfalah'],
    ARRAY['Makkah Region','Mecca','Al Kakiyyah'],
    ARRAY['Makkah Region','Taif','Al Shafa'],
    ARRAY['Makkah Region','Taif','Al Hawiyah'],
    ARRAY['Makkah Region','Taif','Al Faisaliyah'],
    ARRAY['Makkah Region','Rabigh','Rabigh Center'],
    ARRAY['Madinah Region','Medina','Al Awali'],
    ARRAY['Madinah Region','Medina','Al Haram'],
    ARRAY['Madinah Region','Medina','Quba'],
    ARRAY['Madinah Region','Medina','Al Iskan'],
    ARRAY['Madinah Region','Yanbu','Yanbu Al Bahr'],
    ARRAY['Madinah Region','Yanbu','Yanbu Al Sinaiyah'],
    ARRAY['Madinah Region','Al Ula','Al Ula Center'],
    ARRAY['Eastern Province','Dammam','Al Faisaliyah'],
    ARRAY['Eastern Province','Dammam','Al Shati'],
    ARRAY['Eastern Province','Dammam','Al Adamah'],
    ARRAY['Eastern Province','Dammam','Al Mazruiyah'],
    ARRAY['Eastern Province','Khobar','Al Khobar Al Shamalia'],
    ARRAY['Eastern Province','Khobar','Al Khobar Al Janubia'],
    ARRAY['Eastern Province','Khobar','Al Ulaya'],
    ARRAY['Eastern Province','Dhahran','Dhahran Center'],
    ARRAY['Eastern Province','Dhahran','Al Doha'],
    ARRAY['Eastern Province','Jubail','Jubail Center'],
    ARRAY['Eastern Province','Jubail','Al Fanateer'],
    ARRAY['Eastern Province','Al Ahsa','Al Hofuf'],
    ARRAY['Eastern Province','Al Ahsa','Al Mubarraz'],
    ARRAY['Asir Region','Abha','Al Manhal'],
    ARRAY['Asir Region','Abha','Al Shafa'],
    ARRAY['Asir Region','Khamis Mushait','Al Khaleej'],
    ARRAY['Asir Region','Khamis Mushait','Al Rawdah'],
    ARRAY['Asir Region','Bisha','Bisha Center'],
    ARRAY['Tabuk Region','Tabuk','Al Muruj'],
    ARRAY['Tabuk Region','Tabuk','Al Faisaliyah'],
    ARRAY['Tabuk Region','Duba','Duba Center'],
    ARRAY['Tabuk Region','Haql','Haql Center'],
    ARRAY['Hail Region','Hail','Al Muntazah'],
    ARRAY['Hail Region','Hail','Al Khuzama'],
    ARRAY['Hail Region','Hail','Al Nuzha'],
    ARRAY['Northern Borders Region','Arar','Arar Center'],
    ARRAY['Northern Borders Region','Rafha','Rafha Center'],
    ARRAY['Northern Borders Region','Turaif','Turaif Center'],
    ARRAY['Jazan Region','Jazan','Al Rawdah'],
    ARRAY['Jazan Region','Jazan','Al Safa'],
    ARRAY['Jazan Region','Sabya','Sabya Center'],
    ARRAY['Jazan Region','Abu Arish','Abu Arish Center'],
    ARRAY['Najran Region','Najran','Al Faisaliyah'],
    ARRAY['Najran Region','Najran','Al Mukhaym'],
    ARRAY['Najran Region','Sharurah','Sharurah Center'],
    ARRAY['Al Bahah Region','Al Bahah','Al Zahrah'],
    ARRAY['Al Bahah Region','Al Bahah','Al Faisaliyah'],
    ARRAY['Al Bahah Region','Baljurashi','Baljurashi Center'],
    ARRAY['Al Jawf Region','Sakaka','Sakaka Center'],
    ARRAY['Al Jawf Region','Qurayyat','Qurayyat Center'],
    ARRAY['Al Jawf Region','Tabarjal','Tabarjal Center'],
    ARRAY['Al Qassim Region','Buraidah','Al Safra'],
    ARRAY['Al Qassim Region','Buraidah','Al Muruj'],
    ARRAY['Al Qassim Region','Buraidah','Al Iskan'],
    ARRAY['Al Qassim Region','Unayzah','Unayzah Center'],
    ARRAY['Al Qassim Region','Ar Rass','Ar Rass Center']
